"use client"
import React from 'react';
import { ScrollText, AlertCircle, ArrowLeft, CheckCircle2 } from 'lucide-react';
import { motion } from 'framer-motion';
import Link from 'next/link';

function TermsPage() {
    return (
        <div className="min-h-screen bg-background text-foreground pt-24 pb-20 relative overflow-hidden">
            {/* Background Glow */}
            <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-primary/5 blur-[120px] rounded-full -translate-y-1/2 -translate-x-1/2 pointer-events-none" />
            
            <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-3xl relative z-10">
                <Link href="/" className="inline-flex items-center text-muted-foreground hover:text-primary font-black uppercase tracking-widest text-[10px] mb-8 transition-colors group">
                    <ArrowLeft className="w-3 h-3 mr-2 group-hover:-translate-x-1 transition-transform" />
                    BACK TO HOME
                </Link>

                <div className="mb-16">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="inline-block px-4 py-1.5 bg-primary text-white text-[9px] font-black uppercase tracking-widest mb-6 rounded-full"
                    >
                        LEGAL DOCS
                    </motion.div>
                    <motion.h1 
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.1 }}
                        className="text-5xl md:text-7xl lg:text-8xl font-black text-foreground uppercase italic leading-[0.8] tracking-tighter mb-6"
                    >
                        TERMS OF <br />
                        <span className="text-primary not-italic">SERVICE</span>
                    </motion.h1>
                    <p className="text-muted-foreground font-bold uppercase tracking-widest text-[10px]">
                        LAST UPDATED: JANUARY 28, 2026
                    </p>
                </div>

                <div className="space-y-12">
                    <section className="p-12 bg-card/40 backdrop-blur-md border border-border/60 rounded-[48px] hover:bg-card/60 transition-all group shadow-xl shadow-black/5">
                        <p className="text-xl text-foreground font-black uppercase tracking-tighter leading-tight italic">
                            Please read these Terms of Service carefully before using Elisa. Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms.
                        </p>
                    </section>

                    <div className="grid grid-cols-1 gap-10">
                        {[
                            {
                                id: "01",
                                title: "Acceptance of Terms",
                                content: "By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service."
                            },
                            {
                                id: "02",
                                title: "Use License",
                                content: "Permission is granted to temporarily download one copy of the materials on Elisa's website for personal, non-commercial transitory viewing only.",
                                list: [
                                    "MODIFY OR COPY THE MATERIALS",
                                    "USE FOR ANY COMMERCIAL PURPOSE",
                                    "DECOMPILE OR REVERSE ENGINEER",
                                    "REMOVE COPYRIGHT NOTATIONS"
                                ]
                            },
                            {
                                id: "03",
                                title: "Service Availability",
                                content: "We strive to provide continuous availability but do not guarantee that the Service will always be uninterrupted or error-free."
                            },
                            {
                                id: "04",
                                title: "Generated Content",
                                content: "Content generated by our systems is provided 'as is.' You are responsible for reviewing and testing any code generated by our platform."
                            }
                        ].map((item, i) => (
                            <section key={i} className="relative pl-24 group">
                                <div className="absolute left-0 top-0 text-6xl md:text-7xl font-black text-primary/10 group-hover:text-primary transition-colors italic leading-none">{item.id}</div>
                                <h2 className="text-3xl md:text-4xl font-black text-foreground uppercase italic mb-6 tracking-tighter relative z-10">{item.title}</h2>
                                <p className="text-muted-foreground font-black uppercase tracking-[0.2em] text-xs leading-relaxed mb-8 relative z-10">{item.content}</p>
                                {item.list && (
                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 relative z-10">
                                        {item.list.map((li, idx) => (
                                            <div key={idx} className="flex items-center gap-5 p-6 bg-card/40 backdrop-blur-sm border border-border/60 rounded-3xl hover:border-primary transition-all shadow-lg shadow-black/5">
                                                <AlertCircle className="w-5 h-5 text-primary rounded-full shadow-[0_0_8px_rgba(255,0,0,0.3)]" />
                                                <span className="text-[10px] font-black text-foreground uppercase tracking-widest italic">{li}</span>
                                            </div>
                                        ))}
                                    </div>
                                )}
                            </section>
                        ))}
                    </div>

                    <footer className="pt-12 border-t border-border/60">
                        <p className="text-muted-foreground font-black uppercase tracking-[0.3em] text-[9px]">
                            QUESTIONS? CONTACT US AT <a href="mailto:legal@elisa.ai" className="text-primary hover:underline">LEGAL@ELISA.AI</a>
                        </p>
                    </footer>
                </div>
            </div>
        </div>
    );
}

export default TermsPage;






